services:
  - type: web
    name: my-web-app
    env: node
    plan: free
    buildCommand: npm install
    startCommand: node backend/server.js
    envVars:
      - key: NODE_ENV
        value: production
    rootDir: .
    autoDeploy: true
    branch: main
    region: oregon
    healthCheckPath: /
    port: 10000
